# Generated by Django 4.1 on 2022-08-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasemachine',
            name='hourFinish',
            field=models.TimeField(default=''),
        ),
    ]
