# Generated by Django 4.0.6 on 2022-09-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='statusMaint',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
