# Generated by Django 4.1 on 2022-08-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_releasemachine_hourfinish'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.BooleanField(default=False),
        ),
    ]
