# Generated by Django 4.0.6 on 2022-09-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_machine_statusmaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasemachine',
            name='hourFinish',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
